# Generated by Django 5.1.6 on 2025-02-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication_app", "0007_recipe_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipepublic",
            name="instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
